# Generated by Django 3.1.6 on 2021-02-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_url', models.CharField(max_length=127)),
                ('base', models.CharField(default='/', max_length=2047)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_body', models.JSONField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='RequestMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2047)),
                ('value', models.CharField(max_length=2047)),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Query Param'), (2, 'Header')])),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.requestdata')),
            ],
        ),
    ]
