# Generated by Django 3.1.6 on 2021-02-11 20:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='id',
        ),
        migrations.AddField(
            model_name='requestdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='base',
            field=models.CharField(default='', max_length=2047),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='unique_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
