# Generated by Django 3.1.6 on 2021-02-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_auto_20210212_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdata',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='requestmetadata',
            name='request',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='RequestData',
        ),
        migrations.DeleteModel(
            name='RequestMetaData',
        ),
    ]
